### ISSUE TITLE
error 0x01 and 0x03 during installation

### ISSUE THREAD

**Issue by SonTypImInternet** [Niklas20114552/arch-tui-installer#19]
Version: 1.6

- Languages tested: German and Dutch
- Mode tested: Basic and Full
- Drivers choosen: CPU: AMD ; GPU: AMD
- AUR: Chaotic and No Helper

Error message:
`cp: can not stat '/etc/iwd/main.conf' : No such file or directory`

**Comment by SonTypImInternet** [comment]
a solution is to check, whether the main.conf file exists or not:

```bash
if [ -e /etc/iwd/main.conf ]; then
  cp /etc/iwd/main.conf /target/etc/iwd/main.conf
else
  echo "/etc/iwd/main.conf does not exist. Skipped."
fi
```

**Comment by tabbeddev** [comment]
Do I understand you right? Error code 0x01 and 0x03 are displayed during installation?
